name: pulse
description: "Pulse Mobile Application"

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  elementary: ^3.0.0
  elementary_helper: ^1.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  auto_route: ^6.1.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  retrofit: ^4.1.0
  uuid: ^4.3.1
  intl_utils: ^2.8.5
  pretty_dio_logger: ^1.3.1
  mockito: ^5.4.4

  dio: ^5.0.0
  equatable: ^2.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  retrofit_generator: ^8.1.0
  auto_route_generator: ^6.1.0
  json_serializable: ^6.7.1
  freezed: ^2.4.6

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
